---
name: Lint
on:
  push:
    branches-ignore:
      - "s3gw-v*"
    tags-ignore:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v5

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Changed: $file"
          done

      - name: Pre Commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
